keys:
  - &aorus age1rakjuzre4p8gl2426uwrrc0e4tgmjuw9vlkc2pdlp03rtwcun3vsx73a63
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      age:
      - *aorus